# Generated by Django 5.2.8 on 2026-02-25 06:16

import django.db.models.deletion
import wagtail.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('copyright_text', models.CharField(default='© 2025 Все права защищены', max_length=200, verbose_name='Текст копирайта')),
                ('company_address', models.TextField(blank=True, verbose_name='Адрес компании')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Часы работы')),
                ('social_links', wagtail.fields.StreamField([('social', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Платформа', 'max_length': 50}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Ссылка (например, https://facebook.com или #contact)', 'max_length': 200}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Иконка (например, facebook, twitter)', 'max_length': 50}), 3: ('wagtail.blocks.StructBlock', [[('platform', 0), ('href', 1), ('icon', 2)]], {'label': 'Социальная сеть'})}, verbose_name='Социальные сети')),
                ('company_section', wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции', 'max_length': 100, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Текст ссылки', 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Ссылка (например, /about или #contact)', 'max_length': 200}), 3: ('wagtail.blocks.StructBlock', [[('text', 1), ('href', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 4)]], {'label': 'Секция компании'})}, verbose_name='Секции компании')),
                ('solutions_section', wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции', 'max_length': 100, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Текст ссылки', 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Ссылка (например, /solutions или #solutions)', 'max_length': 200}), 3: ('wagtail.blocks.StructBlock', [[('text', 1), ('href', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 4)]], {'label': 'Секция решений'})}, verbose_name='Секции решений')),
                ('services_section', wagtail.fields.StreamField([('item', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции', 'max_length': 100, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Текст ссылки', 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Ссылка (например, /services или #services)', 'max_length': 200}), 3: ('wagtail.blocks.StructBlock', [[('text', 1), ('href', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 4)]], {'label': 'Секция услуг'})}, verbose_name='Секции услуг')),
                ('contact_button_text', models.CharField(default='Связаться с нами', max_length=50, verbose_name='Текст кнопки')),
                ('contact_button_href', models.CharField(blank=True, max_length=200, verbose_name='Ссылка кнопки (например, #contact или /contact)')),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футер',
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('site_title', models.CharField(blank=True, default='', help_text='Название сайта, отображаемое рядом с логотипом', max_length=255)),
                ('consultation_button_text', models.CharField(default='Оставить заявку', help_text='Текст кнопки консультации', max_length=255)),
                ('nav_items', wagtail.fields.StreamField([('nav_item', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название пункта меню', 'label': 'Название пункта*', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Выберите страницу для ссылки', 'label': 'Страница', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Укажите внешний URL, если страница не выбрана', 'label': 'Внешняя ссылка', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Без подменю'), ('simple', 'Простое подменю')], 'help_text': 'Выберите тип подменю', 'label': 'Тип меню*'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название подпункта', 'label': 'Название подпункта*', 'max_length': 255, 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('name', 4), ('page', 1), ('external_url', 2)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': "Используется для типа 'Простое подменю'", 'label': 'Простые элементы подменю', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('name', 0), ('page', 1), ('external_url', 2), ('menu_type', 3), ('simple_dropdown_items', 6)]], {'icon': 'list-ul', 'label': 'Пункт меню'})}, null=True)),
            ],
            options={
                'verbose_name': 'Хидер',
                'verbose_name_plural': 'Хидер',
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Название компании', max_length=100, verbose_name='Название компании')),
                ('address', models.TextField(blank=True, max_length=100, verbose_name='г.Тюмень')),
            ],
            options={
                'verbose_name': 'Инофрмация о сайте',
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('none', 'Нет темы'), ('new_year', 'Новый год (снежинки)'), ('autumn', 'Осень (листья)')], default='none', help_text='Выберите сезонную тему для сайта', max_length=20)),
            ],
            options={
                'verbose_name': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('form_recipient_email', models.EmailField(blank=True, help_text='Email, на который будут отправляться заявки из формы.', max_length=254, verbose_name='Email для заявок')),
                ('section_title', models.CharField(default='Связаться с нами', max_length=100, verbose_name='Заголовок секции')),
                ('section_description', models.TextField(default='Готовы обсудить автоматизацию вашего бизнеса? Свяжитесь с нашими экспертами для получения персональной консультации.', verbose_name='Описание секции')),
                ('primary_phone', models.CharField(blank=True, max_length=20, verbose_name='Основной телефон')),
                ('secondary_phone', models.CharField(blank=True, max_length=20, verbose_name='Дополнительный телефон')),
                ('primary_email', models.EmailField(blank=True, max_length=254, verbose_name='Основной email')),
                ('secondary_email', models.EmailField(blank=True, max_length=254, verbose_name='Дополнительный email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('working_hours', models.TextField(default='Пн-Пт: 9:00 - 18:00, Сб-Вс: по договоренности', verbose_name='Режим работы')),
                ('map_placeholder_text', models.TextField(default='г. Москва, ул. Тверская, д. 15', verbose_name='Текст под картой')),
                ('services', wagtail.fields.StreamField([('service', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название услуги', 'max_length': 100})}, verbose_name='Список услуг')),
                ('form_title', models.CharField(default='Оставить заявку', max_length=100, verbose_name='Заголовок формы')),
                ('privacy_policy_text', models.TextField(default="Нажимая кнопку, вы соглашаетесь с <a href='/privacy-policy/'>политикой обработки персональных данных</a>", verbose_name='Текст политики конфиденциальности')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
    ]
