# Generated by Django 6.0.2 on 2026-03-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='section_description',
            field=models.TextField(default='Готовы обсудить автоматизацию вашего бизнеса?Свяжитесь с нашими экспертами для получения персональной консультации.', verbose_name='Описание секции'),
        ),
    ]
