# Generated by Django 6.0.2 on 2026-02-25 10:57

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
                ('items_per_page', models.PositiveIntegerField(default=9, verbose_name='Кейсов на странице')),
            ],
            options={
                'verbose_name': 'Лента кейсов',
                'verbose_name_plural': 'Лента кейсов',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServiceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
                ('items_per_page', models.PositiveIntegerField(default=9, verbose_name='Услуг на странице')),
            ],
            options={
                'verbose_name': 'Лента услуг',
                'verbose_name_plural': 'Ленты услуг',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CaseStudyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Название компании-клиента')),
                ('industry', models.CharField(choices=[('oil-gas', 'Нефтегаз'), ('manufacturing', 'Производство'), ('construction', 'Строительство'), ('government', 'Госсектор'), ('retail', 'Ритейл'), ('logistics', 'Логистика'), ('finance', 'Финансы'), ('healthcare', 'Здравоохранение')], max_length=100, verbose_name='Отрасль')),
                ('project_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата реализации проекта')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='Длительность проекта')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Местоположение')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='1-3 предложения для анонса', verbose_name='Краткое описание')),
                ('content', wagtail.fields.StreamField([('description', 0), ('challenge', 1), ('solution', 2), ('results', 5), ('technologies', 7), ('metrics', 11)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'image', 'embed', 'code', 'blockquote', 'hr', 'document-link', 'superscript', 'strikethrough'], 'label': 'Описание проекта'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'image', 'embed', 'code', 'blockquote', 'hr', 'document-link', 'superscript', 'strikethrough'], 'label': 'Задача'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'image', 'embed', 'code', 'blockquote', 'hr', 'document-link', 'superscript', 'strikethrough'], 'label': 'Решение'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'label': 'Текст результата'}), 4: ('wagtail.blocks.StructBlock', [[('text', 3)]], {'icon': 'success', 'label': 'Результат'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Результаты '}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Технология'}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Используемые технологии'}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Значение'}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Описание'}), 10: ('wagtail.blocks.StructBlock', [[('value', 8), ('description', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Ключевые метрики'})}, verbose_name='Содержание кейса')),
                ('customer_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Логотип клиента')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Основное изображение')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SingleServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('category', models.CharField(choices=[('consulting', 'Консультации'), ('development', 'Разработка'), ('design', 'Дизайн'), ('support', 'Поддержка'), ('training', 'Обучение'), ('1_c', '1С')], default='consulting', max_length=100, verbose_name='Категория')),
                ('headline', models.CharField(default='Заголовок услуги', max_length=255, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, help_text='1-3 предложения для анонса', verbose_name='Краткое описание')),
                ('content', wagtail.fields.StreamField([('hero', 5), ('text', 7), ('what_we_do', 12), ('description', 15), ('results', 20), ('benefits', 26), ('process', 32), ('technologies', 38), ('gallery', 42), ('video', 45), ('accordion', 51)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок Hero', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок Hero', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение Hero', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('button_text', 3), ('button_link', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 7: ('wagtail.blocks.StructBlock', [[('content', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 9: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание', 'required': True}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Слева'), ('right', 'Справа')], 'label': 'Позиция изображения'}), 12: ('wagtail.blocks.StructBlock', [[('title', 8), ('description', 9), ('image', 10), ('image_position', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'Описание проекта', 'label': 'Заголовок блока', 'required': False}), 14: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'image', 'embed', 'code', 'blockquote', 'hr', 'document-link', 'superscript', 'strikethrough'], 'label': 'Описание', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('title', 13), ('content', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Результаты', 'label': 'Заголовок блока', 'required': False}), 17: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Текст результата', 'required': True}), 18: ('wagtail.blocks.StructBlock', [[('text', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Список результатов'}), 20: ('wagtail.blocks.StructBlock', [[('title', 16), ('items', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'default': 'Ключевые преимущества', 'label': 'Заголовок блока', 'required': False}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Название преимущества', 'required': True}), 23: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('title', 22), ('description', 9), ('icon', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {'label': 'Список преимуществ'}), 26: ('wagtail.blocks.StructBlock', [[('title', 21), ('items', 25)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'Как мы работаем', 'label': 'Заголовок блока', 'required': False}), 28: ('wagtail.blocks.CharBlock', (), {'label': 'Название этапа', 'required': True}), 29: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание этапа', 'required': True}), 30: ('wagtail.blocks.StructBlock', [[('title', 28), ('description', 29)]], {}), 31: ('wagtail.blocks.ListBlock', (30,), {'label': 'Этапы работы'}), 32: ('wagtail.blocks.StructBlock', [[('title', 27), ('items', 31)]], {}), 33: ('wagtail.blocks.CharBlock', (), {'default': 'Технологии и инструменты', 'label': 'Заголовок блока', 'required': False}), 34: ('wagtail.blocks.CharBlock', (), {'label': 'Название технологии', 'required': True}), 35: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Логотип/Иконка', 'required': True}), 36: ('wagtail.blocks.StructBlock', [[('name', 34), ('icon', 35)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {'label': 'Список технологий'}), 38: ('wagtail.blocks.StructBlock', [[('title', 33), ('items', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок галереи', 'required': False}), 40: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 41: ('wagtail.blocks.ListBlock', (40,), {'label': 'Изображения'}), 42: ('wagtail.blocks.StructBlock', [[('title', 39), ('images', 41)]], {}), 43: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок видео', 'required': False}), 44: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Встраиваемое видео (YouTube, Vimeo и т.д.)', 'required': True}), 45: ('wagtail.blocks.StructBlock', [[('title', 43), ('video', 44)]], {}), 46: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок аккордеона', 'required': True}), 47: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос/Заголовок', 'required': True}), 48: ('wagtail.blocks.RichTextBlock', (), {'label': 'Ответ/Описание', 'required': True}), 49: ('wagtail.blocks.StructBlock', [[('question', 47), ('answer', 48)]], {}), 50: ('wagtail.blocks.ListBlock', (49,), {'label': 'Элементы аккордеона'}), 51: ('wagtail.blocks.StructBlock', [[('title', 46), ('items', 50)]], {})}, verbose_name='Блоки страницы')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
            bases=('wagtailcore.page',),
        ),
    ]
