# Generated by Django 6.0.2 on 2026-02-25 12:18

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('achievements', wagtail.fields.StreamField([('main_achievement', 5), ('additional_achievement', 8)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 1: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'label': 'Числовое значение'}), 2: ('wagtail.blocks.CharBlock', (), {'blank': True, 'default': '+', 'label': "Суффикс (например, '+' или '%')", 'max_length': 10}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Краткое название', 'max_length': 100}), 4: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'label': 'Описание достижения'}), 5: ('wagtail.blocks.StructBlock', [[('icon', 0), ('value', 1), ('suffix', 2), ('label', 3), ('description', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Числовое значение или текст', 'max_length': 10}), 7: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Заголовок достижения', 'max_length': 100}), 8: ('wagtail.blocks.StructBlock', [[('value', 6), ('title', 7), ('description', 4)]], {})}, verbose_name='Достижения')),
                ('global_presence', wagtail.fields.StreamField([('presence', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Глобальное присутствие', 'label': 'Заголовок', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link', 'superscript'], 'label': 'Описание', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: квадратное или 1x1', 'label': 'Изображение для локации', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {})}, verbose_name='Глобальное присутствие')),
                ('content', wagtail.fields.StreamField([('hero', 5), ('text', 7), ('what_we_do', 12), ('description', 15), ('results', 20), ('benefits', 26), ('process', 32), ('technologies', 38), ('gallery', 42), ('video', 45), ('accordion', 51), ('cta', 56)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок Hero', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок Hero', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение Hero', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка кнопки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('button_text', 3), ('button_link', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 7: ('wagtail.blocks.StructBlock', [[('content', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 9: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание', 'required': True}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Слева'), ('right', 'Справа')], 'label': 'Позиция изображения'}), 12: ('wagtail.blocks.StructBlock', [[('title', 8), ('description', 9), ('image', 10), ('image_position', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'Описание проекта', 'label': 'Заголовок блока', 'required': False}), 14: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'image', 'embed', 'code', 'blockquote', 'hr', 'document-link', 'superscript', 'strikethrough'], 'label': 'Описание', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('title', 13), ('content', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Результаты', 'label': 'Заголовок блока', 'required': False}), 17: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Текст результата', 'required': True}), 18: ('wagtail.blocks.StructBlock', [[('text', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Список результатов'}), 20: ('wagtail.blocks.StructBlock', [[('title', 16), ('items', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'default': 'Ключевые преимущества', 'label': 'Заголовок блока', 'required': False}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Название преимущества', 'required': True}), 23: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('title', 22), ('description', 9), ('icon', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {'label': 'Список преимуществ'}), 26: ('wagtail.blocks.StructBlock', [[('title', 21), ('items', 25)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'Как мы работаем', 'label': 'Заголовок блока', 'required': False}), 28: ('wagtail.blocks.CharBlock', (), {'label': 'Название этапа', 'required': True}), 29: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание этапа', 'required': True}), 30: ('wagtail.blocks.StructBlock', [[('title', 28), ('description', 29)]], {}), 31: ('wagtail.blocks.ListBlock', (30,), {'label': 'Этапы работы'}), 32: ('wagtail.blocks.StructBlock', [[('title', 27), ('items', 31)]], {}), 33: ('wagtail.blocks.CharBlock', (), {'default': 'Технологии и инструменты', 'label': 'Заголовок блока', 'required': False}), 34: ('wagtail.blocks.CharBlock', (), {'label': 'Название технологии', 'required': True}), 35: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Логотип/Иконка', 'required': True}), 36: ('wagtail.blocks.StructBlock', [[('name', 34), ('icon', 35)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {'label': 'Список технологий'}), 38: ('wagtail.blocks.StructBlock', [[('title', 33), ('items', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок галереи', 'required': False}), 40: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 41: ('wagtail.blocks.ListBlock', (40,), {'label': 'Изображения'}), 42: ('wagtail.blocks.StructBlock', [[('title', 39), ('images', 41)]], {}), 43: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок видео', 'required': False}), 44: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Встраиваемое видео (YouTube, Vimeo и т.д.)', 'required': True}), 45: ('wagtail.blocks.StructBlock', [[('title', 43), ('video', 44)]], {}), 46: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок аккордеона', 'required': True}), 47: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос/Заголовок', 'required': True}), 48: ('wagtail.blocks.RichTextBlock', (), {'label': 'Ответ/Описание', 'required': True}), 49: ('wagtail.blocks.StructBlock', [[('question', 47), ('answer', 48)]], {}), 50: ('wagtail.blocks.ListBlock', (49,), {'label': 'Элементы аккордеона'}), 51: ('wagtail.blocks.StructBlock', [[('title', 46), ('items', 50)]], {}), 52: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок CTA', 'required': True}), 53: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание CTA', 'required': True}), 54: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': True}), 55: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка', 'required': False}), 56: ('wagtail.blocks.StructBlock', [[('title', 52), ('description', 53), ('button_text', 54), ('button_link', 55)]], {})}, verbose_name='Блоки страницы')),
            ],
            options={
                'verbose_name': "Страница 'О компании'",
                'verbose_name_plural': "Страницы 'О компании'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CertificatesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Вступительный текст')),
                ('body', wagtail.fields.StreamField([('certificate', 5)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название сертификата', 'max_length': 200}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Кем выдан', 'max_length': 200}), 2: ('wagtail.blocks.DateBlock', (), {'label': 'Дата выдачи'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Превью сертификата', 'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'PDF сертификата', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('issuer', 1), ('issue_date', 2), ('thumbnail', 3), ('document', 4)]], {})})),
            ],
            options={
                'verbose_name': "Страница 'Сертификаты'",
                'verbose_name_plural': "Страница 'Сертификатов' ",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('address', models.TextField(blank=True, help_text='Полный адрес с индексом', verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('work_hours', models.CharField(blank=True, max_length=200, verbose_name='Режим работы')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Полное наименование')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('okpo', models.CharField(blank=True, max_length=10, verbose_name='ОКПО')),
                ('okved_codes', wagtail.fields.RichTextField(blank=True, verbose_name='Коды ОКВЭД')),
                ('it_activity_codes', wagtail.fields.RichTextField(blank=True, verbose_name='Коды ИТ-деятельности (Приказ Минцифры №449)')),
                ('price_info', wagtail.fields.RichTextField(blank=True, verbose_name='Информация о стоимости услуг')),
                ('software_rights', wagtail.fields.RichTextField(blank=True, verbose_name='Правообладание программным обеспечением')),
                ('technologies', wagtail.fields.RichTextField(blank=True, verbose_name='Технологический стек')),
                ('map_embed_code', models.TextField(blank=True, verbose_name='Код встраивания карты')),
                ('additional_info', wagtail.fields.RichTextField(blank=True, verbose_name='Дополнительная информация')),
                ('dynamic_blocks', wagtail.fields.StreamField([('heading', 2), ('info_card', 6), ('technology_item', 9), ('legal_document', 12), ('contact_method', 16), ('social_link', 20), ('map_block', 23), ('pricing_table', 29), ('accordion', 35)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Подзаголовок', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1)]], {'icon': 'title', 'label': 'Заголовок раздела'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок карточки'}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Содержание'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: fas fa-phone, fas fa-envelope', 'label': 'Класс иконки', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('content', 4), ('icon_class', 5)]], {'icon': 'doc-full', 'label': 'Информационная карточка'}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Название технологии'}), 8: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('name', 7), ('description', 8)]], {'icon': 'code', 'label': 'Технология'}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Название документа'}), 11: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Файл', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 10), ('content', 4), ('file', 11)]], {'icon': 'doc-full-inverse', 'label': 'Юридический документ'}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('phone', 'Телефон'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('viber', 'Viber')], 'label': 'Тип контакта'}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Значение'}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Описание', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('type', 13), ('value', 14), ('description', 15)]], {'icon': 'user', 'label': 'Способ связи'}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('vk', 'ВКонтакте'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('skype', 'Skype')], 'label': 'Платформа'}), 18: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка'}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Текст ссылки', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('platform', 17), ('url', 18), ('text', 19)]], {'icon': 'site', 'label': 'Социальная сеть'}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок карты'}), 22: ('wagtail.blocks.TextBlock', (), {'label': 'Код для вставки карты'}), 23: ('wagtail.blocks.StructBlock', [[('title', 21), ('embed_code', 22), ('description', 8)]], {'icon': 'site', 'label': 'Карта'}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок таблицы'}), 25: ('wagtail.blocks.CharBlock', (), {'label': 'Услуга'}), 26: ('wagtail.blocks.CharBlock', (), {'label': 'Стоимость'}), 27: ('wagtail.blocks.StructBlock', [[('service_name', 25), ('description', 8), ('price', 26)]], {'label': 'Услуга'}), 28: ('wagtail.blocks.ListBlock', (27,), {}), 29: ('wagtail.blocks.StructBlock', [[('title', 24), ('services', 28)]], {'icon': 'table', 'label': 'Таблица цен'}), 30: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок аккордеона'}), 31: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос'}), 32: ('wagtail.blocks.RichTextBlock', (), {'label': 'Ответ'}), 33: ('wagtail.blocks.StructBlock', [[('question', 31), ('answer', 32)]], {'label': 'Элемент'}), 34: ('wagtail.blocks.ListBlock', (33,), {}), 35: ('wagtail.blocks.StructBlock', [[('title', 30), ('items', 34)]], {'icon': 'list-ul', 'label': 'Аккордеон FAQ'})}, verbose_name='Динамические блоки')),
            ],
            options={
                'verbose_name': 'Страница контактов',
                'verbose_name_plural': 'Страницы контактов',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(blank=True, max_length=255, verbose_name='Надзаголовок')),
                ('heading', models.CharField(blank=True, max_length=255, verbose_name='Основной заголовок')),
                ('subheading', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('faq_items', wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Ответ', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {'icon': 'help', 'label': 'Вопрос-ответ'})}, verbose_name='Вопросы и ответы')),
            ],
            options={
                'verbose_name': 'Страница FAQ',
                'verbose_name_plural': 'Страницы FAQ',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
                ('items_per_page', models.PositiveIntegerField(default=9, verbose_name='Новостей на странице')),
            ],
            options={
                'verbose_name': 'Лента новостей',
                'verbose_name_plural': 'Ленты новостей',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('read_time', models.PositiveIntegerField(default=1, help_text='Примерное время чтения статьи в минутах', verbose_name='Время чтения (мин)')),
                ('category', models.CharField(choices=[('company', 'Новости компании'), ('tech', 'Технологии'), ('projects', 'Проекты'), ('events', 'События'), ('awards', 'Награды')], default='company', max_length=100, verbose_name='Категория')),
                ('headline', models.CharField(default='Заголовок новости', max_length=255, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, help_text='1-3 предложения для анонса', verbose_name='Краткое описание')),
                ('media_content', wagtail.fields.StreamField([('image', 2), ('video', 4), ('embed', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {'label': 'Изображение'}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Ссылка на YouTube, Vimeo и т.д.', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('video_url', 3), ('caption', 1)]], {'label': 'Видео'}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Вставьте ссылку на видео (YouTube, Vimeo и т.д.)', 'label': 'Видео (автовставка)'})}, verbose_name='Медиа контент')),
                ('content', wagtail.fields.RichTextField(blank=True, verbose_name='Содержание')),
                ('gallery', wagtail.fields.StreamField([('image', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {'label': 'Изображение галереи'})}, verbose_name='Галерея')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
            bases=('wagtailcore.page',),
        ),
    ]
