# Generated by Django 6.0.2 on 2026-02-26 08:28

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutpage_certificatesindexpage_contactpage_faqpage_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория продукта',
                'verbose_name_plural': 'Категории продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProgramsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
            ],
            options={
                'verbose_name': 'Лента Программ',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('buy_link', models.URLField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('headline', models.CharField(default='Заголовок продукта', max_length=255, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, help_text='1-3 предложения для анонса', verbose_name='Краткое описание')),
                ('content', wagtail.fields.StreamField([('hero', 5), ('text', 7), ('what_we_do', 12), ('description', 15), ('results', 20), ('benefits', 26), ('process', 32), ('technologies', 38), ('gallery', 42), ('video', 45), ('accordion', 51)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок Hero', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок Hero', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение Hero', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка кнопки', 'page_type': ['wagtailcore.Page'], 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('button_text', 3), ('button_link', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 7: ('wagtail.blocks.StructBlock', [[('content', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 9: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание', 'required': True}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Слева'), ('right', 'Справа')], 'label': 'Позиция изображения'}), 12: ('wagtail.blocks.StructBlock', [[('title', 8), ('description', 9), ('image', 10), ('image_position', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'Описание проекта', 'label': 'Заголовок блока', 'required': False}), 14: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'image', 'embed', 'code', 'blockquote', 'hr', 'document-link', 'superscript', 'strikethrough'], 'label': 'Описание', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('title', 13), ('content', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Результаты', 'label': 'Заголовок блока', 'required': False}), 17: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Текст результата', 'required': True}), 18: ('wagtail.blocks.StructBlock', [[('text', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Список результатов'}), 20: ('wagtail.blocks.StructBlock', [[('title', 16), ('items', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'default': 'Ключевые преимущества', 'label': 'Заголовок блока', 'required': False}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Название преимущества', 'required': True}), 23: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('title', 22), ('description', 9), ('icon', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {'label': 'Список преимуществ'}), 26: ('wagtail.blocks.StructBlock', [[('title', 21), ('items', 25)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'Как мы работаем', 'label': 'Заголовок блока', 'required': False}), 28: ('wagtail.blocks.CharBlock', (), {'label': 'Название этапа', 'required': True}), 29: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание этапа', 'required': True}), 30: ('wagtail.blocks.StructBlock', [[('title', 28), ('description', 29)]], {}), 31: ('wagtail.blocks.ListBlock', (30,), {'label': 'Этапы работы'}), 32: ('wagtail.blocks.StructBlock', [[('title', 27), ('items', 31)]], {}), 33: ('wagtail.blocks.CharBlock', (), {'default': 'Технологии и инструменты', 'label': 'Заголовок блока', 'required': False}), 34: ('wagtail.blocks.CharBlock', (), {'label': 'Название технологии', 'required': True}), 35: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Логотип/Иконка', 'required': True}), 36: ('wagtail.blocks.StructBlock', [[('name', 34), ('icon', 35)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {'label': 'Список технологий'}), 38: ('wagtail.blocks.StructBlock', [[('title', 33), ('items', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок галереи', 'required': False}), 40: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 41: ('wagtail.blocks.ListBlock', (40,), {'label': 'Изображения'}), 42: ('wagtail.blocks.StructBlock', [[('title', 39), ('images', 41)]], {}), 43: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок видео', 'required': False}), 44: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Встраиваемое видео (YouTube, Vimeo и т.д.)', 'required': True}), 45: ('wagtail.blocks.StructBlock', [[('title', 43), ('video', 44)]], {}), 46: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок аккордеона', 'required': True}), 47: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос/Заголовок', 'required': True}), 48: ('wagtail.blocks.RichTextBlock', (), {'label': 'Ответ/Описание', 'required': True}), 49: ('wagtail.blocks.StructBlock', [[('question', 47), ('answer', 48)]], {}), 50: ('wagtail.blocks.ListBlock', (49,), {'label': 'Элементы аккордеона'}), 51: ('wagtail.blocks.StructBlock', [[('title', 46), ('items', 50)]], {})}, verbose_name='Блоки страницы')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pages.productcategory', verbose_name='Категория')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
            bases=('wagtailcore.page',),
        ),
    ]
