from .cases import CaseStudyPage
from .cases import CaseStudyIndexPage
from .cases import INDUSTRY_CHOICES
from .about import AboutPage
from .certificates import CertificateBlock,CertificatesIndexPage
from .contact import ContactPage
from .faq import FAQPage
from .news import NewsBlock,NewsIndexPage,NewsPage
from .programs import ProgramsPage,ProductPage
from .services import ServiceBlock,SingleServicePage,ServiceIndexPage
