# Generated by Django 6.0.3 on 2026-03-10 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_company_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер ДИО'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг (URL)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Сотрудник ДИО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='receive_notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worktickets', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mytickets', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
