# Generated by Django 5.2.8 on 2026-02-25 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Вакансия')),
                ('name', models.CharField(verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/%d/', verbose_name='Резюме')),
                ('resume_link', models.URLField(blank=True, null=True, verbose_name='Ссылка для скачивания резюме')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Просмотрено')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики на вакансии',
            },
        ),
        migrations.CreateModel(
            name='VacancyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('responsibilities', models.TextField(verbose_name='Обязанности')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('conditions', models.TextField(verbose_name='Условия')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
            bases=('wagtailcore.page',),
        ),
    ]
